// <auto-generated />
using System;
using FilmDiziTakipApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmDiziTakipApi.Migrations
{
    [DbContext(typeof(UygulamaDB))]
    [Migration("20250614154255_SezonNoEklendi")]
    partial class SezonNoEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmDiziTakipApi.Models.Dizi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiziUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<decimal>("Puan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tur")
                        .HasColumnType("int");

                    b.Property<DateTime>("YayınTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yonetmen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YuklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Dizi");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.DiziBolum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BolumNo")
                        .HasColumnType("int");

                    b.Property<string>("BolumUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SezonId")
                        .HasColumnType("int");

                    b.Property<int>("SezonNo")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ortalamaPuan")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SezonId");

                    b.ToTable("DiziBolum");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.DiziBolumYorumPuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiziBolumId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<string>("Yorum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YorumTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DiziBolumId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("DiziBolumYorumPuan");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.DiziSezon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiziId")
                        .HasColumnType("int");

                    b.Property<int>("SezonNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiziId");

                    b.ToTable("DiziSezon");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilmUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<decimal>("Puan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tur")
                        .HasColumnType("int");

                    b.Property<DateTime>("YayınTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yonetmen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.IzlemeDurumuDizi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiziBolumId")
                        .HasColumnType("int");

                    b.Property<double>("IzlenmeSuresi")
                        .HasColumnType("float");

                    b.Property<DateTime>("IzlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiziBolumId");

                    b.ToTable("IzlemeDurumuDizi");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.IzlemeDurumuFilm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<double>("KalanSure")
                        .HasColumnType("float");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YayinlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("IzlemeDurumuFilm");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategori");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.Puanlama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Deger")
                        .HasColumnType("int");

                    b.Property<int?>("DiziId")
                        .HasColumnType("int");

                    b.Property<int?>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PuanlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yorum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiziId");

                    b.HasIndex("FilmId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Puanlama");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.Yonetici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoneticiAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Yonetici");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.YorumDizi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiziId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("Puan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("YorumMetni")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiziId");

                    b.ToTable("YorumDizi");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.YorumFilm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("Puan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("YorumMetni")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("YorumFilm");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.Dizi", b =>
                {
                    b.HasOne("FilmDiziTakipApi.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.DiziBolum", b =>
                {
                    b.HasOne("FilmDiziTakipApi.Models.DiziSezon", "Sezon")
                        .WithMany("Bolumler")
                        .HasForeignKey("SezonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sezon");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.DiziBolumYorumPuan", b =>
                {
                    b.HasOne("FilmDiziTakipApi.Models.DiziBolum", "DiziBolum")
                        .WithMany("Yorumlar")
                        .HasForeignKey("DiziBolumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmDiziTakipApi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiziBolum");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.DiziSezon", b =>
                {
                    b.HasOne("FilmDiziTakipApi.Models.Dizi", "Dizi")
                        .WithMany("Sezonlar")
                        .HasForeignKey("DiziId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dizi");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.Film", b =>
                {
                    b.HasOne("FilmDiziTakipApi.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.IzlemeDurumuDizi", b =>
                {
                    b.HasOne("FilmDiziTakipApi.Models.DiziBolum", "DiziBolum")
                        .WithMany()
                        .HasForeignKey("DiziBolumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiziBolum");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.IzlemeDurumuFilm", b =>
                {
                    b.HasOne("FilmDiziTakipApi.Models.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmDiziTakipApi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.Puanlama", b =>
                {
                    b.HasOne("FilmDiziTakipApi.Models.Dizi", "Dizi")
                        .WithMany("Puanlamalar")
                        .HasForeignKey("DiziId");

                    b.HasOne("FilmDiziTakipApi.Models.Film", "Film")
                        .WithMany("Puanlamalar")
                        .HasForeignKey("FilmId");

                    b.HasOne("FilmDiziTakipApi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dizi");

                    b.Navigation("Film");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.YorumDizi", b =>
                {
                    b.HasOne("FilmDiziTakipApi.Models.Dizi", null)
                        .WithMany("Yorumlar")
                        .HasForeignKey("DiziId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.YorumFilm", b =>
                {
                    b.HasOne("FilmDiziTakipApi.Models.Film", null)
                        .WithMany("Yorumlar")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.Dizi", b =>
                {
                    b.Navigation("Puanlamalar");

                    b.Navigation("Sezonlar");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.DiziBolum", b =>
                {
                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.DiziSezon", b =>
                {
                    b.Navigation("Bolumler");
                });

            modelBuilder.Entity("FilmDiziTakipApi.Models.Film", b =>
                {
                    b.Navigation("Puanlamalar");

                    b.Navigation("Yorumlar");
                });
#pragma warning restore 612, 618
        }
    }
}
